version: "3.7"

services:
 database:
  image: postgres:14.7
  environment:
   POSTGRES_USER: user
   POSTGRES_PASSWORD: password
   POSTGRES_DB: db
  ports:
   - "5432:5432"
  restart: unless-stopped
